model_name: audio_hubert_stats_mlp
modalities:
  text: false
  audio: false
  audio_hubert: false
  audio_hubert_stats: true
  audio_prosody: false
  audio_hubert_prosody: false
  visual: false

output_dim_audio_hubert_stats: 1536
batch_size_utterance: 64

hidden_dims: [768, 256]
dropout: 0.45
num_classes: 7

optimizer: adamw
learning_rate: 0.00008
weight_decay: 0.0003
max_epochs: 60
early_stopping_patience: 8
loss: weighted_cross_entropy
seed: 114514
