model_name: concat_tav
modalities:
  text: true
  audio: false
  audio_hubert: true
  audio_hubert_stats: false
  audio_prosody: false
  audio_hubert_prosody: false
  visual: false
  visual_face: false
  visual_expression: true

output_dim_text: 768
output_dim_audio_hubert: 768
output_dim_visual_expression: 782
batch_size_utterance: 64

projection_dim: 256
dropout: 0.3
num_classes: 7

optimizer: adamw
learning_rate: 0.0001
weight_decay: 0.0001
max_epochs: 50
early_stopping_patience: 5
loss: weighted_cross_entropy
seed: 114514
