model_name: text_finetune_context5_unweighted

text_model: FacebookAI/roberta-base
local_files_only: true
pooling: cls
max_length: 320
context_window: 5
include_speaker: true
num_classes: 7

dropout: 0.3
batch_size: 8
max_epochs: 8
early_stopping_patience: 3

optimizer: adamw
encoder_lr: 0.00001
classifier_lr: 0.0001
weight_decay: 0.01
warmup_ratio: 0.1
gradient_accumulation_steps: 1
max_grad_norm: 1.0
mixed_precision: true
loss: cross_entropy
seed: 114514
eval_test: true
